### ISSUE TITLE
Resolve duplication issues in README and SUMMARY

### ISSUE THREAD

**Issue by Seasawher** [leanprover-community/lean4-metaprogramming-book#126]
see: https://github.com/leanprover-community/lean4-metaprogramming-book/pull/121#issuecomment-1883837074

summary: README is used for pandoc, SUMMARY for mdbook. These two pieces of information are duplicated, which can lead to forgotten changes.

**Comment by Julian** [comment]
Fixed in #129.

**Comment by Seasawher** [comment]
it is sure that README does not have duplication. but CONTENTS has still duplication.
I think this problem is not fixed yet

**Comment by Julian** [comment]
Ah, true! Thanks.
